In [110]:
import pandas as pd
df = pd.read_csv(r"C:\Users\SATHVIK\OneDrive\Desktop\ncr_ride_bookings.csv")
df.head()

,Date,Time,Booking ID,Booking Status,Customer ID,Vehicle Type,Pickup Location,Drop Location,Avg VTAT,Avg CTAT,...,Reason for cancelling by Customer,Cancelled Rides by Driver,Driver Cancellation Reason,Incomplete Rides,Incomplete Rides Reason,Booking Value,Ride Distance,Driver Ratings,Customer Rating,Payment Method
0,2024-03-23,12:29:38,"""CNR5884300""",No Driver Found,"""CID1982111""",eBike,Palam Vihar,Jhilmil,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2024-11-29,18:01:39,"""CNR1326809""",Incomplete,"""CID4604802""",Go Sedan,Shastri Nagar,Gurgaon Sector 56,4.9,14.0,...,NaN,NaN,NaN,1.0,Vehicle Breakdown,237.0,5.73,NaN,NaN,UPI
2,2024-08-23,08:56:10,"""CNR8494506""",Completed,"""CID9202816""",Auto,Khandsa,Malviya Nagar,13.4,25.8,...,NaN,NaN,NaN,NaN,NaN,627.0,13.58,4.9,4.9,Debit Card
3,2024-10-21,17:17:25,"""CNR8906825""",Completed,"""CID2610914""",Premier Sedan,Central Secretariat,Inderlok,13.1,28.5,...,NaN,NaN,NaN,NaN,NaN,416.0,34.02,4.6,5.0,UPI
4,2024-09-16,22:08:00,"""CNR1950162""",Completed,"""CID9933542""",Bike,Ghitorni Village,Khan Market,5.3,19.6,...,NaN,NaN,NaN,NaN,NaN,737.0,48.21,4.1,4.3,UPI

In [2]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150000 entries, 0 to 149999
Data columns (total 21 columns):
 #   Column                             Non-Null Count   Dtype
---  ------                             --------------   -----
 0   Date                               150000 non-null  object
 1   Time                               150000 non-null  object
 2   Booking ID                         150000 non-null  object
 3   Booking Status                     150000 non-null  object
 4   Customer ID                        150000 non-null  object
 5   Vehicle Type                       150000 non-null  object
 6   Pickup Location                    150000 non-null  object
 7   Drop Location                      150000 non-null  object
 8   Avg VTAT                           139500 non-null  float64
 9   Avg CTAT                           102000 non-null  float64
 10  Cancelled Rides by Customer        10500 non-null   float64
 11  Reason for cancelling by Customer  10500 non-null   object
 12  Cancelled Rides by Driver          27000 non-null   float64
 13  Driver Cancellation Reason         27000 non-null   object
 14  Incomplete Rides                   9000 non-null    float64
 15  Incomplete Rides Reason            9000 non-null    object
 16  Booking Value                      102000 non-null  float64
 17  Ride Distance                      102000 non-null  float64
 18  Driver Ratings                     93000 non-null   float64
 19  Customer Rating                    93000 non-null   float64
 20  Payment Method                     102000 non-null  object
dtypes: float64(9), object(12)
memory usage: 24.0+ MB

In [111]:
df["Booking ID"]=df["Booking ID"].str.replace('"','')
df["Customer ID"]=df["Customer ID"].str.replace('"','')

In [112]:
df["Booking ID"].head()

0    CNR5884300
1    CNR1326809
2    CNR8494506
3    CNR8906825
4    CNR1950162
Name: Booking ID, dtype: object

In [113]:
#convert date,time to date time
df["date_time"]=pd.to_datetime(df["Date"]+" "+df["Time"])

In [114]:
df=df.drop(columns=["Date","Time"])

In [115]:
df.columns

Index(['Booking ID', 'Booking Status', 'Customer ID', 'Vehicle Type',
       'Pickup Location', 'Drop Location', 'Avg VTAT', 'Avg CTAT',
       'Cancelled Rides by Customer', 'Reason for cancelling by Customer',
       'Cancelled Rides by Driver', 'Driver Cancellation Reason',
       'Incomplete Rides', 'Incomplete Rides Reason', 'Booking Value',
       'Ride Distance', 'Driver Ratings', 'Customer Rating', 'Payment Method',
       'date_time'],
      dtype='object')

In [116]:
#converting null strings to nan
df.replace("null",pd.NA,inplace=True)

In [117]:
df.head(2)

,Booking ID,Booking Status,Customer ID,Vehicle Type,Pickup Location,Drop Location,Avg VTAT,Avg CTAT,Cancelled Rides by Customer,Reason for cancelling by Customer,Cancelled Rides by Driver,Driver Cancellation Reason,Incomplete Rides,Incomplete Rides Reason,Booking Value,Ride Distance,Driver Ratings,Customer Rating,Payment Method,date_time
0,CNR5884300,No Driver Found,CID1982111,eBike,Palam Vihar,Jhilmil,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2024-03-23 12:29:38
1,CNR1326809,Incomplete,CID4604802,Go Sedan,Shastri Nagar,Gurgaon Sector 56,4.9,14.0,NaN,NaN,NaN,NaN,1.0,Vehicle Breakdown,237.0,5.73,NaN,NaN,UPI,2024-11-29 18:01:39

In [118]:
df.isnull().sum()

Booking ID                                0
Booking Status                            0
Customer ID                               0
Vehicle Type                              0
Pickup Location                           0
Drop Location                             0
Avg VTAT                              10500
Avg CTAT                              48000
Cancelled Rides by Customer          139500
Reason for cancelling by Customer    139500
Cancelled Rides by Driver            123000
Driver Cancellation Reason           123000
Incomplete Rides                     141000
Incomplete Rides Reason              141000
Booking Value                         48000
Ride Distance                         48000
Driver Ratings                        57000
Customer Rating                       57000
Payment Method                        48000
date_time                                 0
dtype: int64

In [119]:
df["Booking ID"].nunique()

148767

In [93]:
len(df)

150000

In [94]:
#here duplicate items exists so we insopect them first
df[df["Booking ID"].duplicated(keep=False)].sort_values("Booking ID")

,Booking ID,Booking Status,Customer ID,Vehicle Type,Pickup Location,Drop Location,Avg VTAT,Avg CTAT,Cancelled Rides by Customer,Reason for cancelling by Customer,Cancelled Rides by Driver,Driver Cancellation Reason,Incomplete Rides,Incomplete Rides Reason,Booking Value,Ride Distance,Driver Ratings,Customer Rating,Payment Method,date_time
81334,CNR1026036,Completed,CID6480133,Go Mini,Khandsa,Ashok Vihar,3.8,43.3,NaN,NaN,NaN,NaN,NaN,NaN,102.0,36.51,4.9,4.2,UPI,2024-10-15 18:17:23
9192,CNR1026036,No Driver Found,CID6974869,Go Mini,Seelampur,Nehru Place,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2024-07-21 17:59:41
9587,CNR1029172,Completed,CID6382731,Auto,Inderlok,Laxmi Nagar,6.9,34.4,NaN,NaN,NaN,NaN,NaN,NaN,332.0,36.38,4.3,4.3,UPI,2024-12-17 19:19:02
1353,CNR1029172,Incomplete,CID2615731,Bike,Jhilmil,Narsinghpur,4.7,26.7,NaN,NaN,NaN,NaN,1.0,Customer Demand,429.0,16.16,NaN,NaN,UPI,2024-01-19 17:00:57
82029,CNR1051228,Completed,CID3177617,Auto,Dwarka Sector 21,Nehru Place,8.5,24.8,NaN,NaN,NaN,NaN,NaN,NaN,246.0,4.80,4.6,4.5,UPI,2024-11-05 16:50:20
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95375,CNR9962874,Cancelled by Driver,CID9468011,Auto,Narsinghpur,Ardee City,11.0,NaN,NaN,NaN,1.0,Customer related issue,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2024-12-10 10:11:30
57616,CNR9971436,No Driver Found,CID8828441,Uber XL,Jhilmil,Ambience Mall,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2024-02-01 23:46:39
86918,CNR9971436,Incomplete,CID6082697,Go Mini,Hauz Rani,Connaught Place,9.5,18.8,NaN,NaN,NaN,NaN,1.0,Other Issue,287.0,11.68,NaN,NaN,UPI,2024-09-11 12:33:46
17651,CNR9987527,Completed,CID9362124,Auto,Seelampur,Tagore Garden,2.1,17.5,NaN,NaN,NaN,NaN,NaN,NaN,832.0,19.16,4.1,4.9,UPI,2024-03-12 18:20:40
51093,CNR9987527,Completed,CID7979250,Bike,Sadar Bazar Gurgaon,New Delhi Railway Station,9.1,35.9,NaN,NaN,NaN,NaN,NaN,NaN,833.0,29.11,4.2,4.9,Credit Card,2024-01-17 16:44:59

In [95]:
#this has an big issue...we should only keep recent records 
df=df.sort_values("date_time")
df=df.drop_duplicates(subset="Booking ID",keep="last")

In [121]:
df.duplicated().sum()

0

In [123]:
cols = ["Avg VTAT","Avg CTAT","Booking Value","Ride Distance","Driver Ratings","Customer Rating"]

for col in cols:
    df[col] = pd.to_numeric(df[col], errors="coerce")

In [28]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 148767 entries, 122017 to 26151
Data columns (total 20 columns):
 #   Column                             Non-Null Count   Dtype
---  ------                             --------------   -----
 0   Booking ID                         148767 non-null  object
 1   Booking Status                     148767 non-null  object
 2   Customer ID                        148767 non-null  object
 3   Vehicle Type                       148767 non-null  object
 4   Pickup Location                    148767 non-null  object
 5   Drop Location                      148767 non-null  object
 6   Avg VTAT                           138353 non-null  float64
 7   Avg CTAT                           101187 non-null  float64
 8   Cancelled Rides by Customer        10399 non-null   float64
 9   Reason for cancelling by Customer  10399 non-null   object
 10  Cancelled Rides by Driver          26767 non-null   float64
 11  Driver Cancellation Reason         26767 non-null   object
 12  Incomplete Rides                   8943 non-null    float64
 13  Incomplete Rides Reason            8943 non-null    object
 14  Booking Value                      101187 non-null  float64
 15  Ride Distance                      101187 non-null  float64
 16  Driver Ratings                     92244 non-null   float64
 17  Customer Rating                    92244 non-null   float64
 18  Payment Method                     101187 non-null  object
 19  date_time                          148767 non-null  datetime64[ns]
dtypes: datetime64[ns](1), float64(9), object(10)
memory usage: 23.8+ MB

In [122]:
#we use and create other columns
df["hour"]=df["date_time"].dt.hour
df["month"]=df["date_time"].dt.month
df["day_name"]=df["date_time"].dt.day_name

In [34]:
df.columns

Index(['Booking ID', 'Booking Status', 'Customer ID', 'Vehicle Type',
       'Pickup Location', 'Drop Location', 'Avg VTAT', 'Avg CTAT',
       'Cancelled Rides by Customer', 'Reason for cancelling by Customer',
       'Cancelled Rides by Driver', 'Driver Cancellation Reason',
       'Incomplete Rides', 'Incomplete Rides Reason', 'Booking Value',
       'Ride Distance', 'Driver Ratings', 'Customer Rating', 'Payment Method',
       'date_time', 'hour', 'month', 'day_name'],
      dtype='object')

In [124]:
#
df["Booking Status"].value_counts()

Booking Status
Completed                93000
Cancelled by Driver      27000
No Driver Found          10500
Cancelled by Customer    10500
Incomplete                9000
Name: count, dtype: int64

In [125]:
#just chercking that whether cancelee rides can have payment or not
df[(df["Booking Status"]=="Cancelled") & (df["Payment Method"].notna())]

Empty DataFrame
Columns: [Booking ID, Booking Status, Customer ID, Vehicle Type, Pickup Location, Drop Location, Avg VTAT, Avg CTAT, Cancelled Rides by Customer, Reason for cancelling by Customer, Cancelled Rides by Driver, Driver Cancellation Reason, Incomplete Rides, Incomplete Rides Reason, Booking Value, Ride Distance, Driver Ratings, Customer Rating, Payment Method, date_time, hour, month, day_name]
Index: []

[0 rows x 23 columns]

In [126]:
#replacement null values of payment with 0
df["Payment Method"]=df["Payment Method"].fillna("no-payment")

In [127]:
df["Payment Method"].value_counts()

Payment Method
no-payment     48000
UPI            45909
Cash           25367
Uber Wallet    12276
Credit Card    10209
Debit Card      8239
Name: count, dtype: int64

In [128]:
df["Payment Method"]=df["Payment Method"].replace(0,"no payment")

In [129]:
df["Payment Method"].value_counts()

Payment Method
no-payment     48000
UPI            45909
Cash           25367
Uber Wallet    12276
Credit Card    10209
Debit Card      8239
Name: count, dtype: int64

In [130]:
#max of driver and customer rating
print(df["Driver Ratings"].max())

5.0

In [106]:
print(df["Customer Rating"].max())

5.0

In [51]:
df["Cancelled Rides by Customer"] = df["Cancelled Rides by Customer"].fillna(0)
df["Cancelled Rides by Driver"] = df["Cancelled Rides by Driver"].fillna(0)
df["Incomplete Rides"] = df["Incomplete Rides"].fillna(0)

In [107]:
df["Cancelled Rides by Customer"].value_counts()

Cancelled Rides by Customer
1.0    10399
Name: count, dtype: int64

In [64]:
df.loc[df["Booking Status"] != "Completed", "Ride Distance"] = 0
df.loc[df["Booking Status"] != "Completed", "Booking Value"] = 0

In [131]:
df.isnull().sum()

Booking ID                                0
Booking Status                            0
Customer ID                               0
Vehicle Type                              0
Pickup Location                           0
Drop Location                             0
Avg VTAT                              10500
Avg CTAT                              48000
Cancelled Rides by Customer          139500
Reason for cancelling by Customer    139500
Cancelled Rides by Driver            123000
Driver Cancellation Reason           123000
Incomplete Rides                     141000
Incomplete Rides Reason              141000
Booking Value                         48000
Ride Distance                         48000
Driver Ratings                        57000
Customer Rating                       57000
Payment Method                            0
date_time                                 0
hour                                      0
month                                     0
day_name                                  0
dtype: int64

In [134]:
import os
import pandas as pd

# Get username automatically
username = os.getlogin()

# Create full path
desktop_path = f"C:\\Users\\{username}\\Desktop\\cleaned_data12.csv"

# Save
df.to_csv(desktop_path, index=False)

print(f"✅ Saved to: {desktop_path}")

✅ Saved to: C:\Users\SATHVIK\Desktop\cleaned_data12.csv

In [68]:
df.head(22)

,Booking ID,Booking Status,Customer ID,Vehicle Type,Pickup Location,Drop Location,Avg VTAT,Avg CTAT,Cancelled Rides by Customer,Reason for cancelling by Customer,...,Incomplete Rides Reason,Booking Value,Ride Distance,Driver Ratings,Customer Rating,Payment Method,date_time,hour,month,day_name
122017,CNR4352144,Completed,CID8362794,Bike,Udyog Vihar,Ambience Mall,10.8,38.9,0.0,NaN,...,NaN,99.0,37.98,4.8,4.8,Cash,2024-01-01 00:19:34,0,1,<bound method PandasDelegate._add_delegate_acc...
79457,CNR9147645,Completed,CID8300238,Go Mini,Basai Dhankot,Madipur,8.5,15.1,0.0,NaN,...,NaN,114.0,39.29,4.2,4.1,Uber Wallet,2024-01-01 01:35:18,1,1,<bound method PandasDelegate._add_delegate_acc...
19130,CNR1009222,Cancelled by Driver,CID2030746,Go Sedan,Tughlakabad,Greater Kailash,7.4,NaN,0.0,NaN,...,NaN,0.0,0.00,NaN,NaN,no payment,2024-01-01 01:37:50,1,1,<bound method PandasDelegate._add_delegate_acc...
47361,CNR2740479,Cancelled by Driver,CID3231181,Auto,Palam Vihar,Kherki Daula Toll,5.6,NaN,0.0,NaN,...,NaN,0.0,0.00,NaN,NaN,no payment,2024-01-01 01:48:03,1,1,<bound method PandasDelegate._add_delegate_acc...
33452,CNR7650148,Cancelled by Driver,CID3381661,Go Sedan,Narsinghpur,Pulbangash,6.2,NaN,0.0,NaN,...,NaN,0.0,0.00,NaN,NaN,no payment,2024-01-01 01:49:56,1,1,<bound method PandasDelegate._add_delegate_acc...
118744,CNR8140858,Completed,CID9268400,Go Mini,Jhilmil,Welcome,8.1,42.6,0.0,NaN,...,NaN,735.0,39.39,4.3,4.7,UPI,2024-01-01 01:53:01,1,1,<bound method PandasDelegate._add_delegate_acc...
25724,CNR8839592,Cancelled by Driver,CID6577042,Bike,Jama Masjid,Sadar Bazar Gurgaon,11.8,NaN,0.0,NaN,...,NaN,0.0,0.00,NaN,NaN,no payment,2024-01-01 02:14:50,2,1,<bound method PandasDelegate._add_delegate_acc...
11367,CNR4510033,No Driver Found,CID3289424,eBike,Udyog Bhawan,Badarpur,NaN,NaN,0.0,NaN,...,NaN,0.0,0.00,NaN,NaN,no payment,2024-01-01 02:43:46,2,1,<bound method PandasDelegate._add_delegate_acc...
141135,CNR9519641,Cancelled by Driver,CID1177393,Bike,Green Park,Adarsh Nagar,7.7,NaN,0.0,NaN,...,NaN,0.0,0.00,NaN,NaN,no payment,2024-01-01 02:56:49,2,1,<bound method PandasDelegate._add_delegate_acc...
91594,CNR4588428,No Driver Found,CID3087143,Auto,Greater Noida,IMT Manesar,NaN,NaN,0.0,NaN,...,NaN,0.0,0.00,NaN,NaN,no payment,2024-01-01 02:59:14,2,1,<bound method PandasDelegate._add_delegate_acc...
103972,CNR9509351,Cancelled by Driver,CID2180547,Go Sedan,Cyber Hub,Paschim Vihar,10.4,NaN,0.0,NaN,...,NaN,0.0,0.00,NaN,NaN,no payment,2024-01-01 03:13:10,3,1,<bound method PandasDelegate._add_delegate_acc...
47451,CNR6623070,Cancelled by Customer,CID3958529,Go Mini,Anand Vihar,Khandsa,14.3,NaN,1.0,Driver asked to cancel,...,NaN,0.0,0.00,NaN,NaN,no payment,2024-01-01 03:42:12,3,1,<bound method PandasDelegate._add_delegate_acc...
41386,CNR7476971,Cancelled by Driver,CID1133529,Auto,Munirka,Hero Honda Chowk,6.7,NaN,0.0,NaN,...,NaN,0.0,0.00,NaN,NaN,no payment,2024-01-01 03:59:03,3,1,<bound method PandasDelegate._add_delegate_acc...
126107,CNR6073090,Completed,CID7393428,Go Mini,Sarojini Nagar,Madipur,2.9,33.8,0.0,NaN,...,NaN,918.0,44.21,3.6,4.9,Cash,2024-01-01 03:59:29,3,1,<bound method PandasDelegate._add_delegate_acc...
142659,CNR4082656,Completed,CID9685431,eBike,Panchsheel Park,Pragati Maidan,8.6,24.3,0.0,NaN,...,NaN,423.0,40.82,4.4,3.9,Cash,2024-01-01 04:00:07,4,1,<bound method PandasDelegate._add_delegate_acc...
9077,CNR4840689,Completed,CID5104424,Auto,India Gate,Tis Hazari,2.9,39.9,0.0,NaN,...,NaN,296.0,31.45,4.1,4.3,Credit Card,2024-01-01 04:33:29,4,1,<bound method PandasDelegate._add_delegate_acc...
114396,CNR4817997,Completed,CID7644908,Auto,Mundka,Jahangirpuri,10.4,20.9,0.0,NaN,...,NaN,279.0,7.97,3.8,3.9,UPI,2024-01-01 04:41:51,4,1,<bound method PandasDelegate._add_delegate_acc...
131661,CNR5069850,Cancelled by Driver,CID5422980,Bike,Dwarka Sector 21,Punjabi Bagh,5.5,NaN,0.0,NaN,...,NaN,0.0,0.00,NaN,NaN,no payment,2024-01-01 04:53:44,4,1,<bound method PandasDelegate._add_delegate_acc...
3562,CNR4302396,Cancelled by Driver,CID3437829,Auto,Jasola,Vasant Kunj,10.2,NaN,0.0,NaN,...,NaN,0.0,0.00,NaN,NaN,no payment,2024-01-01 05:02:14,5,1,<bound method PandasDelegate._add_delegate_acc...
73812,CNR2812762,Completed,CID3933983,Premier Sedan,IGNOU Road,Moti Nagar,8.5,34.7,0.0,NaN,...,NaN,376.0,33.23,3.6,4.3,UPI,2024-01-01 05:02:51,5,1,<bound method PandasDelegate._add_delegate_acc...
62075,CNR8068543,Cancelled by Driver,CID6433083,Auto,Tughlakabad,Jor Bagh,5.3,NaN,0.0,NaN,...,NaN,0.0,0.00,NaN,NaN,no payment,2024-01-01 05:13:39,5,1,<bound method PandasDelegate._add_delegate_acc...
38215,CNR2053447,Completed,CID6574115,Uber XL,Tilak Nagar,Vatika Chowk,3.1,31.9,0.0,NaN,...,NaN,734.0,16.34,5.0,3.8,UPI,2024-01-01 05:16:57,5,1,<bound method PandasDelegate._add_delegate_acc...

In [80]:
import pandas as pd
import numpy as np

# Replace all <NA> in the DataFrame with NaN
df = df.replace({pd.NA: np.nan})

C:\Users\SATHVIK\AppData\Local\Temp\ipykernel_16336\2463301980.py:5: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df = df.replace({pd.NA: np.nan})

In [84]:
df.head()

,Booking ID,Booking Status,Customer ID,Vehicle Type,Pickup Location,Drop Location,Avg VTAT,Avg CTAT,Cancelled Rides by Customer,Reason for cancelling by Customer,...,Incomplete Rides Reason,Booking Value,Ride Distance,Driver Ratings,Customer Rating,Payment Method,date_time,hour,month,day_name
122017,CNR4352144,Completed,CID8362794,Bike,Udyog Vihar,Ambience Mall,10.8,38.9,0.0,NaN,...,NaN,99.0,37.98,4.8,4.8,Cash,2024-01-01 00:19:34,0,1,<bound method PandasDelegate._add_delegate_acc...
79457,CNR9147645,Completed,CID8300238,Go Mini,Basai Dhankot,Madipur,8.5,15.1,0.0,NaN,...,NaN,114.0,39.29,4.2,4.1,Uber Wallet,2024-01-01 01:35:18,1,1,<bound method PandasDelegate._add_delegate_acc...
19130,CNR1009222,Cancelled by Driver,CID2030746,Go Sedan,Tughlakabad,Greater Kailash,7.4,NaN,0.0,NaN,...,NaN,NaN,0.00,NaN,NaN,no payment,2024-01-01 01:37:50,1,1,<bound method PandasDelegate._add_delegate_acc...
47361,CNR2740479,Cancelled by Driver,CID3231181,Auto,Palam Vihar,Kherki Daula Toll,5.6,NaN,0.0,NaN,...,NaN,NaN,0.00,NaN,NaN,no payment,2024-01-01 01:48:03,1,1,<bound method PandasDelegate._add_delegate_acc...
33452,CNR7650148,Cancelled by Driver,CID3381661,Go Sedan,Narsinghpur,Pulbangash,6.2,NaN,0.0,NaN,...,NaN,NaN,0.00,NaN,NaN,no payment,2024-01-01 01:49:56,1,1,<bound method PandasDelegate._add_delegate_acc...

In [132]:
df.groupby("Vehicle Type")["Ride Distance"].mean()

Vehicle Type
Auto             24.615996
Bike             24.649546
Go Mini          24.612090
Go Sedan         24.609325
Premier Sedan    24.598956
Uber XL          24.402893
eBike            24.990415
Name: Ride Distance, dtype: float64